// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIJMb8A-bRmpr-sQI-J4ctWnUZJHd9j4',
    appId: '1:928147052600:web:53eb162a1281913fb26ecd',
    messagingSenderId: '928147052600',
    projectId: 'kanban-finance-system',
    authDomain: 'kanban-finance-system.firebaseapp.com',
    storageBucket: 'kanban-finance-system.firebasestorage.app',
    measurementId: 'G-C9X8GT5FYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjkKsFjuj32p-fhXuHUGSiVmrY84ptlY',
    appId: '1:928147052600:android:428a3598cfbfbef1b26ecd',
    messagingSenderId: '928147052600',
    projectId: 'kanban-finance-system',
    storageBucket: 'kanban-finance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEEYzoSbjKz_Gue-9G9FWQWgNQptoUBw',
    appId: '1:928147052600:ios:c7f5c4f86537880cb26ecd',
    messagingSenderId: '928147052600',
    projectId: 'kanban-finance-system',
    storageBucket: 'kanban-finance-system.firebasestorage.app',
    iosBundleId: 'com.kanbanfinance.kanbanFinanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuIJMb8A-bRmpr-sQI-J4ctWnUZJHd9j4',
    appId: '1:928147052600:web:e24f7bd1bb0a040eb26ecd',
    messagingSenderId: '928147052600',
    projectId: 'kanban-finance-system',
    authDomain: 'kanban-finance-system.firebaseapp.com',
    storageBucket: 'kanban-finance-system.firebasestorage.app',
    measurementId: 'G-81S0R4Y32E',
  );
}
